/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCapacidadeRouteImport } from './routes/_authenticated/capacidade'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDemandasAvulsasRouteImport } from './routes/_authenticated/demandas-avulsas'
import { Route as AuthenticatedGerenciarUsuariosRouteImport } from './routes/_authenticated/gerenciar-usuarios'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedQuemFazOQueRouteImport } from './routes/_authenticated/quem-faz-o-que'
import { Route as AuthenticatedSelecionarProjetosRouteImport } from './routes/_authenticated/selecionar-projetos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCapacidadeRoute = AuthenticatedCapacidadeRouteImport.update({
  id: '/capacidade',
  path: '/capacidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandasAvulsasRoute =
  AuthenticatedDemandasAvulsasRouteImport.update({
    id: '/demandas-avulsas',
    path: '/demandas-avulsas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGerenciarUsuariosRoute =
  AuthenticatedGerenciarUsuariosRouteImport.update({
    id: '/gerenciar-usuarios',
    path: '/gerenciar-usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuemFazOQueRoute =
  AuthenticatedQuemFazOQueRouteImport.update({
    id: '/quem-faz-o-que',
    path: '/quem-faz-o-que',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSelecionarProjetosRoute =
  AuthenticatedSelecionarProjetosRouteImport.update({
    id: '/selecionar-projetos',
    path: '/selecionar-projetos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/capacidade': typeof AuthenticatedCapacidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas-avulsas': typeof AuthenticatedDemandasAvulsasRoute
  '/gerenciar-usuarios': typeof AuthenticatedGerenciarUsuariosRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/quem-faz-o-que': typeof AuthenticatedQuemFazOQueRoute
  '/selecionar-projetos': typeof AuthenticatedSelecionarProjetosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/capacidade': typeof AuthenticatedCapacidadeRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas-avulsas': typeof AuthenticatedDemandasAvulsasRoute
  '/gerenciar-usuarios': typeof AuthenticatedGerenciarUsuariosRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/quem-faz-o-que': typeof AuthenticatedQuemFazOQueRoute
  '/selecionar-projetos': typeof AuthenticatedSelecionarProjetosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/capacidade': typeof AuthenticatedCapacidadeRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas-avulsas': typeof AuthenticatedDemandasAvulsasRoute
  '/_authenticated/gerenciar-usuarios': typeof AuthenticatedGerenciarUsuariosRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/quem-faz-o-que': typeof AuthenticatedQuemFazOQueRoute
  '/_authenticated/selecionar-projetos': typeof AuthenticatedSelecionarProjetosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/capacidade'
    | '/dashboard'
    | '/demandas-avulsas'
    | '/gerenciar-usuarios'
    | '/planejamento'
    | '/quem-faz-o-que'
    | '/selecionar-projetos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/capacidade'
    | '/dashboard'
    | '/demandas-avulsas'
    | '/gerenciar-usuarios'
    | '/planejamento'
    | '/quem-faz-o-que'
    | '/selecionar-projetos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/capacidade'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas-avulsas'
    | '/_authenticated/gerenciar-usuarios'
    | '/_authenticated/planejamento'
    | '/_authenticated/quem-faz-o-que'
    | '/_authenticated/selecionar-projetos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/capacidade': {
      id: '/_authenticated/capacidade'
      path: '/capacidade'
      fullPath: '/capacidade'
      preLoaderRoute: typeof AuthenticatedCapacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas-avulsas': {
      id: '/_authenticated/demandas-avulsas'
      path: '/demandas-avulsas'
      fullPath: '/demandas-avulsas'
      preLoaderRoute: typeof AuthenticatedDemandasAvulsasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerenciar-usuarios': {
      id: '/_authenticated/gerenciar-usuarios'
      path: '/gerenciar-usuarios'
      fullPath: '/gerenciar-usuarios'
      preLoaderRoute: typeof AuthenticatedGerenciarUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quem-faz-o-que': {
      id: '/_authenticated/quem-faz-o-que'
      path: '/quem-faz-o-que'
      fullPath: '/quem-faz-o-que'
      preLoaderRoute: typeof AuthenticatedQuemFazOQueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selecionar-projetos': {
      id: '/_authenticated/selecionar-projetos'
      path: '/selecionar-projetos'
      fullPath: '/selecionar-projetos'
      preLoaderRoute: typeof AuthenticatedSelecionarProjetosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCapacidadeRoute: typeof AuthenticatedCapacidadeRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasAvulsasRoute: typeof AuthenticatedDemandasAvulsasRoute
  AuthenticatedGerenciarUsuariosRoute: typeof AuthenticatedGerenciarUsuariosRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedQuemFazOQueRoute: typeof AuthenticatedQuemFazOQueRoute
  AuthenticatedSelecionarProjetosRoute: typeof AuthenticatedSelecionarProjetosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCapacidadeRoute: AuthenticatedCapacidadeRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasAvulsasRoute: AuthenticatedDemandasAvulsasRoute,
  AuthenticatedGerenciarUsuariosRoute: AuthenticatedGerenciarUsuariosRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedQuemFazOQueRoute: AuthenticatedQuemFazOQueRoute,
  AuthenticatedSelecionarProjetosRoute: AuthenticatedSelecionarProjetosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
